---
language: ruby
rvm: 2.4.1

before_install:
  - gem install bundler -v "< 2" --no-ri --no-rdoc || true

before_script:
  - "sudo curl -o /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2"

script:
  - "bundle exec rake"
  - "bash shunit2/sed_and_awk_cookbook.sh"

notifications:
  email:
    recipients:
      - 'alexharv074@gmail.com'
    on_success: never
    on_failure: always
