---
theme: jekyll-theme-hacker
name: Alex Harvey
author:
  avatar: /assets/me.jpg
  twitter: alexharv074
  github: https://github.com/alex-harvey-z3q
  email: alexharv074@gmail.com
url: https://alex-harvey-z3q.github.io/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
disqus:
  shortname: alex-harvey-z3q-github-io
feed:
  collections:
    posts:
      categories:
        - puppet
